Adding auth path

diff --git a/pipelines/stable/storefront-springboot/tasks/health-check.yaml b/pipelines/stable/storefront-springboot/tasks/health-check.yaml
--- a/pipelines/stable/storefront-springboot/tasks/health-check.yaml
+++ b/pipelines/stable/storefront-springboot/tasks/health-check.yaml
@@ -21,7 +21,7 @@ spec:
       workingdir: $(inputs.resources.git-source.path)
       env:
         - name: NAMESPACE
-          value: storefront
+          value: storefront-dev
       command: ["/bin/bash"]
       args:
         - -c
@@ -50,14 +50,33 @@ spec:
           sleep 10
 
           echo "Health check start"
-          while [[ $(curl -sL -w "%{http_code}\\n" "${URL}/micro/actuator/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) != "200" ]]; do
-              sleep 30
-              echo "Health check failure. Remaining retries: $sleep_countdown"
-              sleep_countdown=$((sleep_countdown-1))
-              if [[ $sleep_countdown -eq 0 ]]; then
-                      echo "Could not reach health endpoint: ${URL}/micro/actuator/health"
-                      exit 1;
-              fi
-          done
-          echo "Successfully reached health endpoint: ${URL}/micro/actuator/health"
-          echo "====================================================================="
+
+          AUTH_REPO="auth-ms-spring"
+          echo ${AUTH_REPO}
+          echo $(inputs.params.gitRepo)
+
+          if [ $(inputs.params.gitRepo) == ${AUTH_REPO} ]; then
+            while [[ $(curl -sL -w "%{http_code}\\n" "${URL}/actuator/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) != "200" ]]; do
+                sleep 30
+                echo "Health check failure. Remaining retries: $sleep_countdown"
+                sleep_countdown=$((sleep_countdown-1))
+                if [[ $sleep_countdown -eq 0 ]]; then
+                        echo "Could not reach health endpoint: ${URL}/actuator/health"
+                        exit 1;
+                fi
+            done
+            echo "Successfully reached health endpoint: ${URL}/actuator/health"
+            echo "====================================================================="
+          else
+            while [[ $(curl -sL -w "%{http_code}\\n" "${URL}/micro/actuator/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) != "200" ]]; do
+                sleep 30
+                echo "Health check failure. Remaining retries: $sleep_countdown"
+                sleep_countdown=$((sleep_countdown-1))
+                if [[ $sleep_countdown -eq 0 ]]; then
+                        echo "Could not reach health endpoint: ${URL}/micro/actuator/health"
+                        exit 1;
+                fi
+            done
+            echo "Successfully reached health endpoint: ${URL}/micro/actuator/health"
+            echo "====================================================================="
+          fi
